name: Tests

on:
  push:
    branches: [main, dev, feature/tests]
    paths: ["app.py", "tests/", "requirements.txt"]
  pull_request:
    branches: [main]
    paths: ["app.py", "tests/", "requirements.txt"]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # TODO: Ajoutez les étapes manquantes
      # - Setup Python 3.11
      # - Installez les dépendances (requirements.txt + pytest)

      # exemple : comment run pytest
      - name: Run tests
        run: pytest -v